import React, { useState } from 'react';
import { KeyRound, ShieldCheck } from 'lucide-react';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

export default function PasswordChange({ forced = false, onComplete, onCancel }) {
  const [form,setForm]=useState({current_password:'',new_password:'',confirm:''});const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const submit=async event=>{event.preventDefault();if(form.new_password!==form.confirm){setError('New passwords do not match.');return}setBusy(true);setError('');try{await api.post('/auth/change-password',{current_password:form.current_password,new_password:form.new_password});onComplete()}catch(err){setError(getApiErrorMessage(err))}finally{setBusy(false)}};
  return <div className="security-overlay"><section className="glass-card login-card"><div className="login-brand"><div><ShieldCheck size={26}/></div><h1>{forced?'Secure your account':'Change password'}</h1><p>{forced?'Replace the temporary password before continuing.':'Update your NetMonitor sign-in password.'}</p></div>{error&&<div className="notice error">{error}</div>}<form onSubmit={submit}><div className="form-group"><label className="form-label">Current password</label><input className="form-input" type="password" autoComplete="current-password" required value={form.current_password} onChange={e=>setForm({...form,current_password:e.target.value})}/></div><div className="form-group"><label className="form-label">New password</label><input className="form-input" type="password" minLength="9" autoComplete="new-password" required value={form.new_password} onChange={e=>setForm({...form,new_password:e.target.value})}/></div><div className="form-group"><label className="form-label">Confirm new password</label><input className="form-input" type="password" minLength="9" autoComplete="new-password" required value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></div><small className="field-hint">Use at least 9 characters.</small><div className="row-actions"><button className="btn btn-primary" disabled={busy}><KeyRound size={16}/>{busy?'Updating…':'Update password'}</button>{!forced&&<button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button>}</div></form></section></div>;
}
