import React, { useState } from 'react';
import { Mail, Search, UserRoundSearch } from 'lucide-react';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

const empty={username:'',email:'',display_name:'',role:'VIEWER'};
const Field=({label,children})=><div className="form-group"><label className="form-label">{label}</label>{children}</div>;

export default function UserManagement({report}) {
  const[items,setItems]=useState([]);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false);const[query,setQuery]=useState('');const[roleFilter,setRoleFilter]=useState('');const[searched,setSearched]=useState(false);const[searching,setSearching]=useState(false);
  const searchUsers=async event=>{event?.preventDefault();if(!query.trim()&&!roleFilter){setItems([]);setSearched(false);report('error','Enter a username, email, display name, or select a role.');return}setSearching(true);try{const response=await api.get('/auth/users',{params:{q:query.trim()||undefined,role:roleFilter||undefined,limit:50}});setItems(response.data);setSearched(true)}catch(error){report('error',getApiErrorMessage(error))}finally{setSearching(false)}};
  const create=async event=>{event.preventDefault();setBusy(true);try{await api.post('/auth/users',form);setForm(empty);report('success','User invited. A temporary password was sent by email.');if(searched)await searchUsers()}catch(error){report('error',getApiErrorMessage(error))}finally{setBusy(false)}};
  const update=async(item,changes)=>{try{await api.put(`/auth/users/${item.id}`,changes);report('success','User updated.');await searchUsers()}catch(error){report('error',getApiErrorMessage(error))}};
  const changeProfile=item=>{const displayName=window.prompt(`Full name for ${item.username}`,item.display_name||'');if(displayName===null||!displayName.trim())return;const email=window.prompt(`Email address for ${item.username}`,item.email||'');if(email===null||!email.trim())return;if(displayName.trim()!==item.display_name||email.trim()!==item.email)update(item,{display_name:displayName.trim(),email:email.trim()})};
  const changeEmail=changeProfile;
  return <div className="settings-grid user-admin-grid">
    <form className="glass-card settings-panel user-invite-form" onSubmit={create}><div className="panel-heading"><div><h3>Invite user</h3><p className="muted">A temporary password is generated and delivered through SMTP.</p></div><Mail size={20}/></div><div className="form-row"><Field label="Username"><input className="form-input" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label="Display name"><input className="form-input" required value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></Field></div><Field label="Email address"><input className="form-input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Role"><select className="form-select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>VIEWER</option><option>OPERATOR</option><option>ADMINISTRATOR</option></select></Field><div className="form-actions"><button className="btn btn-primary" disabled={busy}><Mail size={15}/>{busy?'Sending invitation…':'Create and send invitation'}</button></div></form>
    <section className="glass-card settings-panel user-directory"><div className="panel-heading"><div><h3>User directory</h3><p className="muted">Search without loading the complete user directory.</p></div><UserRoundSearch size={20}/></div><form className="user-search-bar" onSubmit={searchUsers}><div className="form-group"><label className="form-label">Username, email, or display name</label><input className="form-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users…"/></div><div className="form-group"><label className="form-label">Role</label><select className="form-select" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">Any role</option><option>VIEWER</option><option>OPERATOR</option><option>ADMINISTRATOR</option></select></div><button className="btn btn-primary" disabled={searching}><Search size={15}/>{searching?'Searching…':'Search'}</button></form>{!searched?<div className="user-search-empty"><UserRoundSearch size={32}/><strong>Search for a user</strong><span>Results are limited to 50 records.</span></div>:!items.length?<div className="user-search-empty"><UserRoundSearch size={32}/><strong>No matching users</strong><span>Try another email, username, name, or role.</span></div>:<div className="user-results"><div className="user-result-summary">{items.length} matching user(s){items.length===50?' · refine the search for more precision':''}</div>{items.map(item=><article className="user-result" key={item.id}><div className="user-identity"><strong>{item.display_name}</strong><span>@{item.username}</span><small>{item.email||'Email not registered'}</small>{item.must_change_password&&<small className="pending-access">First-access password change pending</small>}</div><div className="user-controls"><button type="button" className="btn btn-secondary" onClick={()=>changeEmail(item)}>Edit email</button><select aria-label={`Role for ${item.username}`} className="form-select compact" value={item.role} onChange={e=>update(item,{role:e.target.value})}><option>VIEWER</option><option>OPERATOR</option><option>ADMINISTRATOR</option></select><button type="button" className={`btn ${item.enabled?'btn-danger':'btn-primary'}`} onClick={()=>update(item,{enabled:!item.enabled})}>{item.enabled?'Disable':'Enable'}</button></div></article>)}</div>}</section>
  </div>;
}
