import React, { useCallback, useEffect, useState } from 'react';
import { Activity, Bell, CheckCircle, Filter, Radio, RefreshCw, X } from 'lucide-react';
import api from '../api/client';
import Pagination from '../components/Pagination';
import { getApiErrorMessage } from '../utils/errors';

const defaults={search:'',start:'',end:'',limit:'100',page:'1',target_type:'',target_id:'',status:'',severity:'',alert_state:''};
const dateBoundary=(date,endOfDay)=>new Date(`${date}T${endOfDay?'23:59:59.999':'00:00:00'}`).toISOString();
const params=(filters,tab)=>{const query=new URLSearchParams();['search','start','end','limit','page'].forEach(key=>filters[key]&&query.set(key,['start','end'].includes(key)?dateBoundary(filters[key],key==='end'):filters[key]));if(tab==='probes'){['target_type','target_id','status'].forEach(key=>filters[key]&&query.set(key,filters[key]))}else{if(filters.severity)query.set('severity',filters.severity);if(filters.alert_state)query.set('is_resolved',String(filters.alert_state==='resolved'))}return query.toString()};

export default function History(){
 const[tab,setTab]=useState('probes');const[filters,setFilters]=useState(defaults);const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[inventory,setInventory]=useState({devices:[],links:[],groups:[]});
 const fetchData=useCallback(async()=>{setLoading(true);setError('');try{const url=tab==='probes'?`/history/probes?${params(filters,tab)}`:`/alerts?${params(filters,tab)}`;const response=await api.get(url);setRows(response.data);setTotal(Number(response.headers['x-total-count']??response.data.length))}catch(err){setError(getApiErrorMessage(err))}finally{setLoading(false)}},[tab,filters]);
 useEffect(()=>{fetchData();const timer=setInterval(fetchData,15000);return()=>clearInterval(timer)},[fetchData]);useEffect(()=>{Promise.all([api.get('/devices'),api.get('/links'),api.get('/redundancy-groups')]).then(([devices,links,groups])=>setInventory({devices:devices.data,links:links.data,groups:groups.data})).catch(()=>{})},[]);const change=e=>setFilters(old=>({...old,[e.target.name]:e.target.value,page:'1',...(e.target.name==='target_type'?{target_id:''}:{})}));const targetOptions=filters.target_type==='DEVICE'?inventory.devices:filters.target_type==='LINK'?inventory.links:filters.target_type==='REDUNDANCY_GROUP'?inventory.groups:[];
 return <div className="data-page"><div className="page-title"><div><h2>Network Operations History</h2><p>Search and filter monitoring probes and the complete incident history.</p></div><button className="btn btn-secondary" onClick={fetchData} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/> Refresh</button></div>
 <div className="history-tabs"><button className={tab==='probes'?'active':''} onClick={()=>setTab('probes')}><Activity size={16}/> Monitoring Probes</button><button className={tab==='alerts'?'active':''} onClick={()=>setTab('alerts')}><Bell size={16}/> Alert History</button></div>
 <div className="glass-card filter-panel"><div className="filter-panel-title"><Filter size={16}/><strong>History filters</strong><button onClick={()=>setFilters(defaults)}><X size={14}/> Clear filters</button></div><div className="filter-grid"><div className="form-group filter-search"><label className="form-label">Search</label><input name="search" className="form-input" placeholder={tab==='probes'?'Device, IP, or link':'Title, message, or cause'} value={filters.search} onChange={change}/></div>{tab==='probes'?<><div className="form-group"><label className="form-label">Target type</label><select name="target_type" className="form-select" value={filters.target_type} onChange={change}><option value="">All targets</option><option>DEVICE</option><option>LINK</option><option>REDUNDANCY_GROUP</option></select></div><div className="form-group"><label className="form-label">Target</label><select name="target_id" className="form-select" value={filters.target_id} onChange={change} disabled={!filters.target_type}><option value="">{filters.target_type?'All selected targets':'Select a target type first'}</option>{targetOptions.map(item=><option key={item.id} value={item.id}>{item.name}{filters.target_type==='DEVICE'&&item.ip_address?` — ${item.ip_address}`:''}</option>)}</select></div><div className="form-group"><label className="form-label">Probe status</label><select name="status" className="form-select" value={filters.status} onChange={change}><option value="">All states</option><option>UP</option><option>DOWN</option><option>DEGRADED</option><option>UNKNOWN</option></select></div></>:<><div className="form-group"><label className="form-label">Severity</label><select name="severity" className="form-select" value={filters.severity} onChange={change}><option value="">All severities</option><option>INFORMATION</option><option>WARNING</option><option>CRITICAL</option></select></div><div className="form-group"><label className="form-label">State</label><select name="alert_state" className="form-select" value={filters.alert_state} onChange={change}><option value="">All states</option><option value="active">Active</option><option value="resolved">Resolved</option></select></div></>}<div className="form-group"><label className="form-label">From date</label><input name="start" type="date" className="form-input" value={filters.start} onChange={change}/></div><div className="form-group"><label className="form-label">To date</label><input name="end" type="date" className="form-input" value={filters.end} onChange={change}/></div><div className="form-group"><label className="form-label">Limit</label><select name="limit" className="form-select" value={filters.limit} onChange={change}><option>50</option><option>100</option><option>250</option><option>500</option></select></div></div></div>
 {error&&<div className="notice error">{error}</div>}<div className="result-summary">{loading?'Loading history…':`${rows.length} record(s) found`}</div>
 <div className="glass-card history-table-wrap">{!loading&&!rows.length?<div className="filtered-empty">{tab==='probes'?<Radio size={30}/>:<CheckCircle size={30}/>}<strong>No records match these filters</strong><span>Change the date range or clear some filters.</span></div>:<table className="custom-table"><thead>{tab==='probes'?<tr><th>Date and time</th><th>Target</th><th>Type</th><th>Status</th><th>Latency</th><th>Packet loss</th></tr>:<tr><th>Triggered</th><th>Resolved</th><th>Severity</th><th>Title / cause</th><th>Status</th></tr>}</thead><tbody>{tab==='probes'?rows.map(item=>{const status=item.status||'UNKNOWN';return <tr key={item.id}><td>{item.timestamp?new Date(item.timestamp).toLocaleString():'—'}</td><td><strong>{item.target_name}</strong><small>#{item.target_id}</small></td><td>{item.target_type}</td><td><span className={`badge badge-${status==='UP'?'online':status.toLowerCase()}`}>{status}</span></td><td>{item.latency_ms==null?'—':`${item.latency_ms} ms`}</td><td>{item.packet_loss_pct==null?'—':`${item.packet_loss_pct}%`}</td></tr>}):rows.map(item=>{const severity=item.severity||'INFORMATION';return <tr key={item.id}><td>{item.created_at?new Date(item.created_at).toLocaleString():'—'}</td><td>{item.resolved_at?new Date(item.resolved_at).toLocaleString():'—'}</td><td><span className={`badge badge-${severity.toLowerCase()}`}>{severity}</span></td><td><strong>{item.title||'Untitled alert'}</strong>{item.root_cause&&<small>{item.root_cause}</small>}</td><td>{item.is_resolved?'RESOLVED':'ACTIVE'}</td></tr>})}</tbody></table>}</div>
 <Pagination page={Number(filters.page)} pageSize={Number(filters.limit)} total={total} count={rows.length} disabled={loading} onPageChange={page=>setFilters(old=>({...old,page:String(page)}))}/></div>
}
