import React, { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle, CircleCheck, CircleX, Database, RefreshCw, Search } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';
import '../styles/metrics.css';

export default function MetricsDiscovery(){
  const navigate=useNavigate(); const [params]=useSearchParams(); const requestedDevice=params.get('device')||''; const autoLoaded=useRef(false);
  const [devices,setDevices]=useState([]); const [deviceId,setDeviceId]=useState(requestedDevice); const [integration,setIntegration]=useState(null); const [integrationLoading,setIntegrationLoading]=useState(false); const [result,setResult]=useState(null); const [selected,setSelected]=useState(new Set()); const [interfaces,setInterfaces]=useState([]); const [selectedInterfaces,setSelectedInterfaces]=useState(new Set()); const [interfaceSearch,setInterfaceSearch]=useState('');
  const [thresholds,setThresholds]=useState({cpu:{enabled:true,warning:80,critical:90},memory:{enabled:true,warning:80,critical:90},storage:{enabled:true,warning:80,critical:90}}); const [notifications,setNotifications]=useState(true); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(null);
  useEffect(()=>{api.get('/devices').then(r=>setDevices(r.data));},[]); const device=devices.find(x=>String(x.id)===String(deviceId));
  const loadIntegration=async id=>{setIntegrationLoading(true);try{const rows=await Promise.all(['windows-monitoring','linux-monitoring','snmp-monitoring'].map(path=>api.get(`/devices/${id}/${path}`).then(r=>[path,r.data])));const active=rows.find(([,value])=>value?.enabled);setIntegration(active?{provider:active[0],connection:active[1]}:null);}catch(error){setIntegration(null);setNotice({type:'error',text:getApiErrorMessage(error)});}finally{setIntegrationLoading(false);}};
  const choose=id=>{setDeviceId(String(id));setIntegration(null);setResult(null);setSelected(new Set());setInterfaces([]);setSelectedInterfaces(new Set());setNotice(null);loadIntegration(id);};
  const discover=async()=>{setBusy('discover');setNotice(null);try{const {data}=await api.get(`/devices/${deviceId}/metrics/capabilities`);setResult(data);setSelected(new Set(Array.isArray(data.enabled_metrics)?data.enabled_metrics:Object.entries(data.capabilities).filter(([,item])=>item.supported).map(([key])=>key)));setThresholds(current=>({...current,...data.metric_thresholds}));setNotifications(data.metric_notifications_enabled!==false);if(integration?.provider==='snmp-monitoring'&&data.capabilities.network_interfaces?.supported){const inventory=(await api.get(`/devices/${deviceId}/metrics/interfaces`)).data;setInterfaces(inventory.interfaces);setSelectedInterfaces(new Set(inventory.selected_interface_indexes));}}catch(error){setNotice({type:'error',text:getApiErrorMessage(error)});}finally{setBusy('');}};
  useEffect(()=>{if(deviceId)loadIntegration(deviceId);},[deviceId]);
  useEffect(()=>{if(requestedDevice&&String(deviceId)===requestedDevice&&integration&&!integrationLoading&&!autoLoaded.current){autoLoaded.current=true;discover();}},[requestedDevice,deviceId,integration,integrationLoading]);
  const save=async()=>{setBusy('save');setNotice(null);try{const {data}=await api.put(`/devices/${deviceId}/metrics/configuration`,{enabled_metrics:[...selected],metric_thresholds:thresholds,selected_interface_indexes:[...selectedInterfaces],metric_notifications_enabled:notifications});const cleared=data.resolved_alerts?` ${data.resolved_alerts} inactive threshold alert(s) were closed.`:'';setNotice({type:'success',text:(selected.size?'Metric monitoring saved. The collector will retrieve each provider independently.':'Metric monitoring disabled for this device.')+cleared});}catch(error){setNotice({type:'error',text:`Metrics were not saved: ${getApiErrorMessage(error)}`});}finally{setBusy('');}};
  const updateThreshold=(key,field,value)=>setThresholds(old=>({...old,[key]:{...old[key],[field]:field==='enabled'?value:Number(value)}})); const toggle=key=>setSelected(old=>{const next=new Set(old);next.has(key)?next.delete(key):next.add(key);return next;});
  return <div className="data-page"><div className="page-title"><div><h2>Discover Metrics</h2><p>Discover supported telemetry from an active Services Monitoring integration.</p></div><button className="btn btn-secondary" onClick={()=>navigate('/metrics-monitoring')}>Return to Metrics</button></div>{notice&&<div className={`notice ${notice.type}`}>{notice.text}</div>}
    <section className="glass-card service-wizard-card wide"><div className="wizard-heading"><Database size={28}/><div><h3>Select an integrated device</h3><p>Configure WinRM, SSH, or SNMP first in Services Monitoring → Discovery. Metrics uses that active integration securely.</p></div></div><DeviceCombo devices={devices} value={deviceId} onChange={choose}/>{device&&<><div className="selected-device-summary"><span className={`service-health-dot state-${device.status==='ONLINE'?'up':'down'}`}/><div><strong>{device.name}</strong><small>{device.ip_address||'No IP'} {'·'} {device.device_type}</small></div><b>{device.status}</b></div><IntegrationFeedback integration={integration} loading={integrationLoading}/><div className="wizard-actions"><button className="btn btn-secondary" onClick={()=>navigate(`/service-discovery?device=${device.id}`)}>{integration?'Manage Service Integration':'Configure Service Integration'}</button><button className="btn btn-primary" disabled={device.status!=='ONLINE'||!!busy||!integration} onClick={discover}><RefreshCw size={15} className={busy==='discover'?'spin':''}/>Discover supported metrics</button></div></>}</section>
    {result&&<section className="glass-card analytics-panel metrics-capabilities"><div className="panel-title"><div><h3>Supported metrics on {result.device_name}</h3><p>Select categories to monitor. Only capabilities returned by the active integration can be enabled.</p></div></div><div className="capability-grid">{Object.entries(result.capabilities).map(([key,item])=><label key={key} className={`${item.supported?'supported':'unsupported'} ${selected.has(key)?'selected':''}`}><input type="checkbox" disabled={!item.supported} checked={selected.has(key)} onChange={()=>toggle(key)}/><CheckCircle size={18}/><div><strong>{item.label}</strong><small>{item.supported?'Supported by the active integration':'Not supported by the active integration'}</small></div></label>)}</div>{integration?.provider==='snmp-monitoring'&&selected.has('network_interfaces')&&<SNMPInterfaces interfaces={interfaces} selected={selectedInterfaces} search={interfaceSearch} setSearch={setInterfaceSearch} toggle={index=>setSelectedInterfaces(old=>{const next=new Set(old);next.has(index)?next.delete(index):next.add(index);return next;})}/>}<div className="metric-thresholds"><div><h4>Alert thresholds</h4><p>Create alerts when selected percentage metrics exceed these limits.</p></div>{[['cpu','CPU'],['memory','Memory'],['storage','Highest disk usage']].map(([key,label])=><div className="metric-threshold-row" key={key}><label><input type="checkbox" checked={thresholds[key]?.enabled!==false} disabled={!selected.has(key)} onChange={e=>updateThreshold(key,'enabled',e.target.checked)}/>{label}</label><Field label="Warning %"><input className="form-input" type="number" min="0" max="100" disabled={!selected.has(key)||thresholds[key]?.enabled===false} value={thresholds[key]?.warning??80} onChange={e=>updateThreshold(key,'warning',e.target.value)}/></Field><Field label="Critical %"><input className="form-input" type="number" min="0" max="100" disabled={!selected.has(key)||thresholds[key]?.enabled===false} value={thresholds[key]?.critical??90} onChange={e=>updateThreshold(key,'critical',e.target.value)}/></Field></div>)}<label className="check-line"><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/>Send configured notifications when a metric alert is created</label></div><div className="wizard-actions"><span>{selected.size} categories selected</span><button className="btn btn-primary" disabled={!!busy} onClick={save}>{busy==='save'?'Saving…':selected.size?'Save Metrics & Thresholds':'Stop Metric Monitoring'}</button></div></section>}
  </div>;
}
function DeviceCombo({devices,value,onChange}){const[query,setQuery]=useState('');const[open,setOpen]=useState(false);const chosen=devices.find(x=>String(x.id)===String(value));const matches=useMemo(()=>{const term=query.trim().toLowerCase();return term?devices.filter(x=>`${x.name} ${x.ip_address||''} ${x.device_type}`.toLowerCase().includes(term)):[];},[devices,query]);return <div className="device-combobox metrics-device-combobox" onBlur={()=>setOpen(false)}><div className="device-combobox-input"><Search size={17}/><input className="form-input" value={open?query:(chosen?`${chosen.name} · ${chosen.ip_address||'No IP'}`:'')} placeholder="Search device or IP…" onFocus={()=>{setOpen(true);setQuery('')}} onChange={e=>{setQuery(e.target.value);setOpen(true)}}/></div>{open&&<div className="device-combobox-menu">{!query.trim()?<div className="device-combobox-empty">Type a device name or IP to search</div>:matches.length?matches.map(x=><button key={x.id} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.id);setOpen(false);setQuery('')}}><span className={`service-health-dot state-${x.status==='ONLINE'?'up':'down'}`}/><div><strong>{x.name}</strong><small>{x.ip_address||'No IP'} · {x.device_type}</small></div><b>{x.status}</b></button>):<div className="device-combobox-empty">No matching devices</div>}</div>}</div>}
function IntegrationFeedback({integration,loading}){if(loading)return <div className="service-defaults-note"><RefreshCw size={15} className="spin"/><span>Checking Services Monitoring integration…</span></div>;if(!integration)return <div className="service-defaults-note integration-missing"><CircleX size={17}/><div><strong>No active integration</strong><span>Configure WinRM, SSH, or SNMP in Services Monitoring before discovering metrics.</span></div></div>;const label={"windows-monitoring":"Windows / WinRM","linux-monitoring":"Linux / SSH","snmp-monitoring":"SNMP"}[integration.provider];return <div className="service-defaults-note integration-ready"><CircleCheck size={17}/><div><strong>{label} integration active</strong><span>Port {integration.connection.port} · Ready to discover metrics supported by this integration.</span></div></div>}
function SNMPInterfaces({interfaces,selected,search,setSearch,toggle}){const rows=interfaces.filter(item=>`${item.name} ${item.type||''} ${item.index}`.toLowerCase().includes(search.toLowerCase()));return <div className="metric-thresholds"><div><h4>SNMP interface selection</h4><p>Select only interfaces that should be stored and used for traffic/utilization calculations.</p></div><div className="search-wrapper"><Search size={16}/><input className="form-input" placeholder="Search interface name, type, or index…" value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="device-picker-list">{rows.map(item=><label className="check-line" key={item.index}><input type="checkbox" checked={selected.has(item.index)} onChange={()=>toggle(item.index)}/><span>{item.name}</span><small>#{item.index} · {item.type||'Unknown'} · {item.oper_status||'unknown'}</small></label>)}{!rows.length&&<span className="muted">No interfaces match this search.</span>}</div><small className="muted">{selected.size} interface(s) selected. Traffic appears after at least two collections.</small></div>}
function Field({label,children}){return <div className="form-group"><label className="form-label">{label}</label>{children}</div>}
