import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Cpu, HardDrive, MemoryStick, Network, RefreshCw, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';
import '../styles/metrics.css';

const bytes=value=>value==null?'—':value>=1073741824?`${(value/1073741824).toFixed(1)} GB`:value>=1048576?`${(value/1048576).toFixed(1)} MB`:`${value} B`;
const uptime=value=>value==null?'—':`${Math.floor(value/86400)}d ${Math.floor(value%86400/3600)}h`;
export default function MetricsMonitoring(){
  const navigate=useNavigate(); const [rows,setRows]=useState([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=()=>{setLoading(true);api.get('/metrics/overview').then(r=>{setRows(r.data);setError('');}).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false));};
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[]);
  const visible=useMemo(()=>rows.filter(x=>!search||`${x.device.name} ${x.device.ip_address||''}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
  const latest=rows[0]?.latest;
  return <div className="data-page"><div className="page-title"><div><h2>Metrics Monitoring</h2><p>Windows system, storage, network, process, and event telemetry.</p></div><div className="row-actions"><button className="btn btn-secondary" onClick={load}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button><button className="btn btn-primary" onClick={()=>navigate('/metrics-discovery')}>Discover Metrics</button></div></div>{error&&<div className="notice error">{error}</div>}
    <div className="service-kpi-grid"><Metric icon={Cpu} label="CPU" value={latest?.cpu_percent==null?'—':`${latest.cpu_percent}%`}/><Metric icon={MemoryStick} label="Memory" value={latest?.memory_percent==null?'—':`${latest.memory_percent}%`}/><Metric icon={Activity} label="Uptime" value={uptime(latest?.uptime_seconds)}/><Metric icon={Network} label="Interfaces" value={latest?.network_interfaces?.length||0}/></div>
    <section className="glass-card analytics-panel"><div className="panel-title"><div><h3>Monitored devices</h3><p>Latest normalized Windows metrics by device.</p></div></div><div className="search-wrapper metrics-search"><Search size={16}/><input className="form-input" placeholder="Search device or IP…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="metrics-device-grid">{visible.map(({device,latest:item})=><article key={device.id} className="metrics-device-card"><header onDoubleClick={()=>navigate(`/devices/${device.id}`)}><div><strong>{device.name}</strong><span>{device.ip_address||'No IP'}</span></div><span className={`badge badge-${device.status==='ONLINE'?'online':'offline'}`}>{device.status}</span></header><div className="metrics-values"><span><Cpu size={15}/>CPU <b>{item.cpu_percent??'—'}%</b></span><span><MemoryStick size={15}/>Memory <b>{item.memory_percent??'—'}%</b></span><span><Activity size={15}/>Uptime <b>{uptime(item.uptime_seconds)}</b></span><span><HardDrive size={15}/>Disks <b>{item.storage?.length||0}</b></span><span><Network size={15}/>Interfaces <b>{item.network_interfaces?.length||0}</b></span></div><small>Collected {new Date(item.collected_at).toLocaleString()}</small><MetricDetails item={item}/></article>)}</div>{!loading&&!visible.length&&<div className="service-placeholder"><Activity size={32}/><span>No metric snapshots available. Discover metrics and collect the first snapshot.</span></div>}</section>
  </div>;
}
function Metric({icon:Icon,label,value}){return <div className="glass-card service-kpi"><Icon size={22}/><div><span>{label}</span><strong>{value}</strong></div></div>}
function MetricDetails({item}){return <details className="metric-details"><summary>View collected details</summary><div className="metric-detail-sections"><section><h4>System information</h4><dl>{Object.entries(item.system_information||{}).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'—')}</dd></div>)}</dl></section><section><h4>Storage</h4>{item.storage?.map(x=><p key={x.name}><strong>{x.name} {x.label}</strong><span>{x.used_percent}% used · {bytes(x.free_bytes)} free / {bytes(x.size_bytes)}</span></p>)}</section><section><h4>Network interfaces</h4>{item.network_interfaces?.map(x=><p key={x.name}><strong>{x.name}</strong><span>↓ {bytes(x.bytes_received_per_sec)}/s · ↑ {bytes(x.bytes_sent_per_sec)}/s · Errors {Number(x.packets_received_errors||0)+Number(x.packets_outbound_errors||0)}</span></p>)}</section><section><h4>Top processes</h4>{item.processes?.slice(0,10).map(x=><p key={`${x.name}-${x.process_id}`}><strong>{x.name} (PID {x.process_id})</strong><span>CPU {x.cpu_percent}% · Memory {bytes(x.working_set_bytes)}</span></p>)}</section><section><h4>Recent critical events</h4>{item.events?.slice(0,10).map((x,i)=><p key={`${x.event_code}-${i}`}><strong>{x.source} · Event {x.event_code}</strong><span>{x.message||'No event message'}</span></p>)}</section></div></details>}
