import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle, Database, RefreshCw, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';
import '../styles/metrics.css';

export default function MetricsDiscovery(){
  const navigate=useNavigate(); const [devices,setDevices]=useState([]); const [deviceId,setDeviceId]=useState(''); const [query,setQuery]=useState(''); const [result,setResult]=useState(null); const [selected,setSelected]=useState(new Set()); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(null);
  useEffect(()=>{api.get('/devices').then(r=>setDevices(r.data));},[]); const device=devices.find(x=>String(x.id)===deviceId); const matches=useMemo(()=>devices.filter(x=>`${x.name} ${x.ip_address||''} ${x.device_type}`.toLowerCase().includes(query.toLowerCase())),[devices,query]);
  const choose=id=>{setDeviceId(String(id));setResult(null);setSelected(new Set());};
  const discover=async()=>{setBusy('discover');setNotice(null);try{const {data}=await api.get(`/devices/${deviceId}/metrics/capabilities`);setResult(data);setSelected(new Set(data.enabled_metrics?.length?data.enabled_metrics:Object.entries(data.capabilities).filter(([,v])=>v.supported).map(([k])=>k)));}catch(e){setNotice({type:'error',text:getApiErrorMessage(e)});}finally{setBusy('');}};
  const save=async()=>{setBusy('save');try{await api.put(`/devices/${deviceId}/metrics/configuration`,{enabled_metrics:[...selected]});await api.post(`/devices/${deviceId}/metrics/collect`);setNotice({type:'success',text:'Metric monitoring saved and the first snapshot was collected.'});}catch(e){setNotice({type:'error',text:getApiErrorMessage(e)});}finally{setBusy('');}};
  const toggle=key=>setSelected(old=>{const next=new Set(old);next.has(key)?next.delete(key):next.add(key);return next;});
  return <div className="data-page"><div className="page-title"><div><h2>Discover Windows Metrics</h2><p>Detect only the telemetry categories supported by the selected host.</p></div><button className="btn btn-secondary" onClick={()=>navigate('/metrics-monitoring')}>Return to Metrics</button></div>{notice&&<div className={`notice ${notice.type}`}>{notice.text}</div>}
    <section className="glass-card service-wizard-card wide"><div className="wizard-heading"><Database size={28}/><div><h3>Select a registered device</h3><p>The same saved Windows monitoring connection is used securely.</p></div></div><div className="search-wrapper metrics-search"><Search size={16}/><input className="form-input" placeholder="Search device or IP…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="metrics-device-selector">{matches.map(x=><button key={x.id} className={String(x.id)===deviceId?'selected':''} onClick={()=>choose(x.id)}><span className={`service-health-dot state-${x.status==='ONLINE'?'up':'down'}`}/><div><strong>{x.name}</strong><small>{x.ip_address||'No IP'} · {x.device_type}</small></div><b>{x.status}</b></button>)}</div>{device&&<div className="wizard-actions"><span/><button className="btn btn-primary" disabled={device.status!=='ONLINE'||!!busy} onClick={discover}><RefreshCw size={15} className={busy==='discover'?'spin':''}/>Discover supported metrics</button></div>}</section>
    {result&&<section className="glass-card analytics-panel metrics-capabilities"><div className="panel-title"><div><h3>Supported metrics on {result.device_name}</h3><p>Select categories to monitor. Unsupported capabilities cannot be enabled.</p></div></div><div className="capability-grid">{Object.entries(result.capabilities).map(([key,item])=><label key={key} className={`${item.supported?'supported':'unsupported'} ${selected.has(key)?'selected':''}`}><input type="checkbox" disabled={!item.supported} checked={selected.has(key)} onChange={()=>toggle(key)}/><CheckCircle size={18}/><div><strong>{item.label}</strong><small>{item.supported?'Supported by this host':'Not available on this host'}</small></div></label>)}</div><div className="wizard-actions"><span>{selected.size} categories selected</span><button className="btn btn-primary" disabled={!selected.size||!!busy} onClick={save}>{busy==='save'?'Saving and collecting…':'Monitor Selected Metrics'}</button></div></section>}
  </div>;
}
