import React, { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle, Database, RefreshCw, Search } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';
import '../styles/metrics.css';

export default function MetricsDiscovery(){
  const navigate=useNavigate(); const [params]=useSearchParams(); const requestedDevice=params.get('device')||''; const autoLoaded=useRef(false); const [devices,setDevices]=useState([]); const [deviceId,setDeviceId]=useState(requestedDevice); const [result,setResult]=useState(null); const [selected,setSelected]=useState(new Set()); const [thresholds,setThresholds]=useState({cpu:{enabled:true,warning:80,critical:90},memory:{enabled:true,warning:80,critical:90},storage:{enabled:true,warning:80,critical:90}}); const [notifications,setNotifications]=useState(true); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(null);
  useEffect(()=>{api.get('/devices').then(r=>setDevices(r.data));},[]); const device=devices.find(x=>String(x.id)===deviceId);
  const choose=id=>{setDeviceId(String(id));setResult(null);setSelected(new Set());};
  const discover=async()=>{setBusy('discover');setNotice(null);try{const {data}=await api.get(`/devices/${deviceId}/metrics/capabilities`);setResult(data);setSelected(new Set(Array.isArray(data.enabled_metrics)?data.enabled_metrics:Object.entries(data.capabilities).filter(([,v])=>v.supported).map(([k])=>k)));setThresholds(current=>({...current,...data.metric_thresholds}));setNotifications(data.metric_notifications_enabled!==false);}catch(e){setNotice({type:'error',text:getApiErrorMessage(e)});}finally{setBusy('');}};
  useEffect(()=>{if(requestedDevice&&deviceId===requestedDevice&&!autoLoaded.current){autoLoaded.current=true;discover();}},[requestedDevice,deviceId]);
  const save=async()=>{setBusy('save');try{await api.put(`/devices/${deviceId}/metrics/configuration`,{enabled_metrics:[...selected],metric_thresholds:thresholds,metric_notifications_enabled:notifications});if(selected.size)await api.post(`/devices/${deviceId}/metrics/collect`);setNotice({type:'success',text:selected.size?'Metric monitoring and alert thresholds updated.':'Metric monitoring disabled for this device.'});}catch(e){setNotice({type:'error',text:getApiErrorMessage(e)});}finally{setBusy('');}};
  const updateThreshold=(key,field,value)=>setThresholds(old=>({...old,[key]:{...old[key],[field]:field==='enabled'?value:Number(value)}}));
  const toggle=key=>setSelected(old=>{const next=new Set(old);next.has(key)?next.delete(key):next.add(key);return next;});
  return <div className="data-page"><div className="page-title"><div><h2>Discover Metrics</h2><p>Detect only the telemetry categories supported by the selected host and provider.</p></div><button className="btn btn-secondary" onClick={()=>navigate('/metrics-monitoring')}>Return to Metrics</button></div>{notice&&<div className={`notice ${notice.type}`}>{notice.text}</div>}
    <section className="glass-card service-wizard-card wide"><div className="wizard-heading"><Database size={28}/><div><h3>Select a registered device</h3><p>The saved Windows or Linux monitoring connection is used securely.</p></div></div><DeviceCombo devices={devices} value={deviceId} onChange={choose}/>{device&&<div className="wizard-actions"><span/><button className="btn btn-primary" disabled={device.status!=='ONLINE'||!!busy} onClick={discover}><RefreshCw size={15} className={busy==='discover'?'spin':''}/>Discover supported metrics</button></div>}</section>
    {result&&<section className="glass-card analytics-panel metrics-capabilities"><div className="panel-title"><div><h3>Supported metrics on {result.device_name}</h3><p>Select categories to monitor. Clear all selections to stop metric monitoring for this device.</p></div></div><div className="capability-grid">{Object.entries(result.capabilities).map(([key,item])=><label key={key} className={`${item.supported?'supported':'unsupported'} ${selected.has(key)?'selected':''}`}><input type="checkbox" disabled={!item.supported} checked={selected.has(key)} onChange={()=>toggle(key)}/><CheckCircle size={18}/><div><strong>{item.label}</strong><small>{item.supported?'Supported by this host':'Not available on this host'}</small></div></label>)}</div><div className="metric-thresholds"><div><h4>Alert thresholds</h4><p>Create alerts when selected percentage metrics exceed these limits.</p></div>{[['cpu','CPU'],['memory','Memory'],['storage','Highest disk usage']].map(([key,label])=><div className="metric-threshold-row" key={key}><label><input type="checkbox" checked={thresholds[key]?.enabled!==false} disabled={!selected.has(key)} onChange={e=>updateThreshold(key,'enabled',e.target.checked)}/>{label}</label><Field label="Warning %"><input className="form-input" type="number" min="0" max="100" disabled={!selected.has(key)||thresholds[key]?.enabled===false} value={thresholds[key]?.warning??80} onChange={e=>updateThreshold(key,'warning',e.target.value)}/></Field><Field label="Critical %"><input className="form-input" type="number" min="0" max="100" disabled={!selected.has(key)||thresholds[key]?.enabled===false} value={thresholds[key]?.critical??90} onChange={e=>updateThreshold(key,'critical',e.target.value)}/></Field></div>)}<label className="check-line"><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/>Send configured notifications when a metric alert is created</label></div><div className="wizard-actions"><span>{selected.size} categories selected</span><button className="btn btn-primary" disabled={!!busy} onClick={save}>{busy==='save'?'Saving…':selected.size?'Save Metrics & Thresholds':'Stop Metric Monitoring'}</button></div></section>}
  </div>;
}

function DeviceCombo({devices,value,onChange}){
  const [query,setQuery]=useState(''); const [open,setOpen]=useState(false); const chosen=devices.find(x=>String(x.id)===String(value));
  const matches=useMemo(()=>{const term=query.trim().toLowerCase();return term?devices.filter(x=>`${x.name} ${x.ip_address||''} ${x.device_type}`.toLowerCase().includes(term)):[];},[devices,query]);
  return <div className="device-combobox metrics-device-combobox" onBlur={()=>setOpen(false)}><div className="device-combobox-input"><Search size={17}/><input className="form-input" value={open?query:(chosen?`${chosen.name} · ${chosen.ip_address||'No IP'}`:'')} placeholder="Search device or IP…" onFocus={()=>{setOpen(true);setQuery('')}} onChange={e=>{setQuery(e.target.value);setOpen(true)}}/></div>{open&&<div className="device-combobox-menu">{!query.trim()?<div className="device-combobox-empty">Type a device name or IP to search</div>:matches.length?matches.map(x=><button key={x.id} className={String(x.id)===String(value)?'selected':''} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.id);setOpen(false);setQuery('')}}><span className={`service-health-dot state-${x.status==='ONLINE'?'up':'down'}`}/><div><strong>{x.name}</strong><small>{x.ip_address||'No IP'} · {x.device_type}</small></div><b>{x.status}</b></button>):<div className="device-combobox-empty">No matching devices</div>}</div>}</div>;
}
function Field({label,children}){return <div className="form-group"><label className="form-label">{label}</label>{children}</div>}
