import React, { useEffect, useState } from 'react';
import { Bell, Database, Download, Image, Plus, Save, Settings, TestTube, Trash2, Upload } from 'lucide-react';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';
import NotificationSettings from '../components/NotificationSettings';

const databaseBlank = { name: '', database_type: 'POSTGRESQL', host: '', port: 5432, database_name: '', username: '', password: '', ssl_enabled: false, enabled: true };
const databaseDefaultPorts = { POSTGRESQL: 5432, MYSQL: 3306, MSSQL: 1433, ORACLE: 1521, SQLITE: null };

export default function PlatformSettings() {
  const [tab, setTab] = useState('databases');
  const [notice, setNotice] = useState(null);
  const tabs = [['databases', Database, 'Databases'], ['notifications', Bell, 'Notifications'], ['icons', Image, 'Icons'], ['general', Settings, 'System & Backup']];
  const report = (type, text) => setNotice({ type, text });
  return <div>
    <div className="page-title"><div><h2>Configuration and Integrations</h2><p>Persistent settings, protected credentials, and controlled tests.</p></div></div>
    <div className="settings-tabs">{tabs.map(([key, Icon, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon size={16} />{label}</button>)}</div>
    {notice && <div className={`notice ${notice.type}`}>{notice.text}</div>}
    {tab === 'databases' && <Databases report={report} />}
    {tab === 'notifications' && <NotificationSettings report={report} />}
    {tab === 'icons' && <Icons report={report} />}
    {tab === 'general' && <General report={report} />}
  </div>;
}

function Databases({ report }) {
  const [items, setItems] = useState([]); const [form, setForm] = useState(databaseBlank); const [editing, setEditing] = useState(null); const [busy, setBusy] = useState(false); const [runtime,setRuntime]=useState(null);
  const [sources,setSources]=useState([]); const [source,setSource]=useState({connection_id:'',name:'',query_text:'SELECT 1 AS status',parameters:{},enabled:true});
  const load = () => Promise.all([api.get('/platform/databases'),api.get('/platform/data-sources'),api.get('/platform/database-runtime')]).then(([connections,dataSources,current])=>{setItems(connections.data);setSources(dataSources.data);setRuntime(current.data);}).catch(e => report('error', getApiErrorMessage(e)));
  useEffect(() => { load(); }, []);
  const edit = item => { setEditing(item.id); setForm({ ...item, password: '' }); };
  const changeDatabaseType = databaseType => setForm(current => ({
    ...current,
    database_type: databaseType,
    port: databaseDefaultPorts[databaseType],
    host: databaseType === 'SQLITE' ? '' : current.host,
  }));
  const save = async e => { e.preventDefault(); setBusy(true); try { editing ? await api.put(`/platform/databases/${editing}`, form) : await api.post('/platform/databases', form); report('success', 'Connection saved securely.'); setEditing(null); setForm(databaseBlank); load(); } catch(e) { report('error', getApiErrorMessage(e)); } finally { setBusy(false); } };
  const test = async id => { try { const r = await api.post(`/platform/databases/${id}/test`); report(r.data.status === 'SUCCESS' ? 'success' : 'error', r.data.message); load(); } catch(e) { report('error', getApiErrorMessage(e)); } };
  const remove = async id => { if (!confirm('Delete this connection?')) return; await api.delete(`/platform/databases/${id}`); load(); };
  const activate=async item=>{if(!confirm(`Migrate all data to "${item.name}" and make it the primary database? The destination database must be empty.`))return;setBusy(true);try{const r=await api.post(`/platform/databases/${item.id}/activate`);report('success',`${r.data.migrated_records} records migrated and validated. Restart the backend to activate ${item.name}.`);}catch(err){report('error',getApiErrorMessage(err));}finally{setBusy(false);}};
  const createSource=async e=>{e.preventDefault();try{await api.post('/platform/data-sources',{...source,connection_id:Number(source.connection_id)});setSource({connection_id:'',name:'',query_text:'SELECT 1 AS status',parameters:{},enabled:true});report('success','Data source created.');load();}catch(err){report('error',getApiErrorMessage(err));}};
  const testSource=async id=>{try{const r=await api.post(`/platform/data-sources/${id}/test`);report(r.data.status==='SUCCESS'?'success':'error',r.data.status==='SUCCESS'?`Valid query: ${r.data.row_count} row(s).`:r.data.message);load();}catch(err){report('error',getApiErrorMessage(err));}};
  return <><div className="settings-grid"><form className="glass-card settings-panel" onSubmit={save}><h3>{editing ? 'Edit Connection' : 'New Connection'}</h3>
    <Field label="Name"><input className="form-input" required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></Field>
    <div className="form-row"><Field label="Type"><select className="form-select" value={form.database_type} onChange={e => changeDatabaseType(e.target.value)}>{['POSTGRESQL','MYSQL','MSSQL','ORACLE','SQLITE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Database / file"><input className="form-input" required value={form.database_name} onChange={e => setForm({...form,database_name:e.target.value})}/></Field></div>
    {form.database_type !== 'SQLITE' && <><div className="form-row"><Field label="Host"><input className="form-input" required value={form.host||''} onChange={e=>setForm({...form,host:e.target.value})}/></Field><Field label="Port"><input className="form-input" type="number" value={form.port||''} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></Field></div><div className="form-row"><Field label="User"><input className="form-input" value={form.username||''} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label={editing && form.password_configured ? 'New password (leave blank to keep current)' : 'Password'}><input className="form-input" type="password" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/></Field></div></>}
    <label className="check-line"><input type="checkbox" checked={form.ssl_enabled} onChange={e=>setForm({...form,ssl_enabled:e.target.checked})}/> SSL enabled</label><button className="btn btn-primary" disabled={busy}><Save size={16}/>Save Connection</button>
  </form><div className="glass-card settings-panel"><h3>Configured Connections</h3>{runtime&&<div className="current-database"><span>CURRENT PRIMARY DATABASE</span><strong>{runtime.name}</strong><small>{runtime.database_type}</small></div>}{!items.length?<p className="muted">No connections configured. Local SQLite remains the primary database.</p>:items.map(item=><div className="integration-row" key={item.id}><div><strong>{item.name}</strong><span>{item.database_type} · {item.host || item.database_name}</span></div><span className={`badge badge-${runtime?.connection_id===item.id?'online':item.last_status==='FAILED'?'offline':'unknown'}`}>{runtime?.connection_id===item.id?'PRIMARY':item.last_status}</span><div className="row-actions"><button className="btn btn-secondary" onClick={()=>test(item.id)}><TestTube size={14}/>Test</button>{runtime?.connection_id!==item.id&&<button className="btn btn-primary" disabled={busy} onClick={()=>activate(item)}>Use as Primary</button>}<button className="btn btn-secondary" onClick={()=>edit(item)}>Edit</button><button className="btn btn-danger" disabled={runtime?.connection_id===item.id} onClick={()=>remove(item.id)}><Trash2 size={14}/></button></div></div>)}</div></div>
  <div className="settings-grid" style={{marginTop:'18px'}}><form className="glass-card settings-panel" onSubmit={createSource}><h3>New Data Source</h3><Field label="Connection"><select required className="form-select" value={source.connection_id} onChange={e=>setSource({...source,connection_id:e.target.value})}><option value="">Select</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Name"><input required className="form-input" value={source.name} onChange={e=>setSource({...source,name:e.target.value})}/></Field><Field label="Read-only Query"><textarea required className="form-input" rows="4" value={source.query_text} onChange={e=>setSource({...source,query_text:e.target.value})}/></Field><button className="btn btn-primary"><Plus size={15}/>Create Source</button></form><div className="glass-card settings-panel"><h3>Available Sources</h3>{!sources.length?<p className="muted">No sources configured.</p>:sources.map(x=><div className="integration-row" key={x.id}><div><strong>{x.name}</strong><span>{items.find(i=>i.id===x.connection_id)?.name} · SELECT limited to 100 rows</span></div><span className={`badge badge-${x.last_status==='SUCCESS'?'online':x.last_status==='FAILED'?'offline':'unknown'}`}>{x.last_status}</span><div className="row-actions"><button className="btn btn-secondary" onClick={()=>testSource(x.id)}><TestTube size={14}/>Run</button><button className="btn btn-danger" onClick={async()=>{if(confirm('Delete source?')){await api.delete(`/platform/data-sources/${x.id}`);load();}}}><Trash2 size={14}/></button></div></div>)}</div></div></>;
}


function Icons({ report }) { const [icons,setIcons]=useState([]); const [name,setName]=useState(''); const [file,setFile]=useState(null); const load=()=>api.get('/platform/icons').then(r=>setIcons(r.data)); useEffect(()=>{load();},[]); const upload=async e=>{e.preventDefault();const data=new FormData();data.append('name',name);data.append('category','Custom');data.append('file',file);try{await api.post('/platform/icons',data,{headers:{'Content-Type':'multipart/form-data'}});report('success','Icon uploaded.');setName('');setFile(null);load();}catch(err){report('error',getApiErrorMessage(err));}}; return <div className="settings-grid"><form className="glass-card settings-panel" onSubmit={upload}><h3>Custom Icon</h3><p className="muted">Sanitized SVG or PNG, up to 512 KB.</p><Field label="Name"><input className="form-input" required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="File"><input className="form-input" required type="file" accept=".svg,.png,image/svg+xml,image/png" onChange={e=>setFile(e.target.files[0])}/></Field><button className="btn btn-primary"><Upload size={15}/>Upload</button></form><div className="glass-card settings-panel"><h3>Library ({icons.length})</h3><div className="icon-library">{icons.map(i=><div key={i.id}><span>{i.lucide_name||'SVG/PNG'}</span><strong>{i.name}</strong><small>{i.category}</small></div>)}</div></div></div> }

function General({ report }) { const [form,setForm]=useState({timezone:'UTC',retention_days:90,default_monitoring_interval:30,failure_threshold:3,success_threshold:2}); useEffect(()=>{api.get('/platform/settings').then(r=>setForm(r.data));},[]); const save=async e=>{e.preventDefault();try{await api.put('/platform/settings',form);report('success','Settings saved.');}catch(err){report('error',getApiErrorMessage(err));}}; const backup=async()=>{const r=await api.get('/platform/configuration/export');const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`netmonitor-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}; const restore=async file=>{try{const payload=JSON.parse(await file.text());const r=await api.post('/platform/configuration/import',payload);report('success',`Backup imported: ${Object.values(r.data.counts).reduce((a,b)=>a+b,0)} records processed.`);}catch(err){report('error',getApiErrorMessage(err));}}; return <div className="settings-grid"><form className="glass-card settings-panel" onSubmit={save}><h3>Persistent Preferences</h3><Field label="Timezone"><input className="form-input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field><div className="form-row"><Field label="Retention (days)"><input className="form-input" type="number" value={form.retention_days} onChange={e=>setForm({...form,retention_days:Number(e.target.value)})}/></Field><Field label="Default interval (s)"><input className="form-input" type="number" value={form.default_monitoring_interval} onChange={e=>setForm({...form,default_monitoring_interval:Number(e.target.value)})}/></Field></div><button className="btn btn-primary"><Save size={15}/>Save</button></form><div className="glass-card settings-panel"><h3>Backup and Restore</h3><p className="muted">Credentials are never included in the exported file.</p><div className="backup-actions"><button className="btn btn-primary" onClick={backup}><Download size={15}/>Export Configuration</button><label className="btn btn-secondary"><Upload size={15}/>Import Backup<input hidden type="file" accept="application/json" onChange={e=>e.target.files[0]&&restore(e.target.files[0])}/></label></div></div></div> }

function Field({ label, children }) { return <div className="form-group"><label className="form-label">{label}</label>{children}</div>; }
