import React, { useEffect, useState } from 'react';
import { Bell, Database, Download, Image, Plus, Save, Settings, TestTube, Trash2, Upload } from 'lucide-react';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

const databaseBlank = { name: '', database_type: 'POSTGRESQL', host: '', port: 5432, database_name: '', username: '', password: '', ssl_enabled: false, enabled: true };
const providerDefaults = {
  EMAIL: { provider: 'EMAIL', name: 'Email SMTP', enabled: false, config: { smtp_server: '', smtp_port: 587, username: '', from_address: '', recipients: [], tls: true, ssl: false }, secrets: { password: '' } },
  TELEGRAM: { provider: 'TELEGRAM', name: 'Telegram', enabled: false, config: { chat_id: '' }, secrets: { bot_token: '' } },
  WHATSAPP: { provider: 'WHATSAPP', name: 'WhatsApp API', enabled: false, config: { api_url: '', sender_id: '', recipient: '' }, secrets: { api_token: '' } },
};

export default function PlatformSettings() {
  const [tab, setTab] = useState('databases');
  const [notice, setNotice] = useState(null);
  const tabs = [['databases', Database, 'Bases de dados'], ['notifications', Bell, 'Notificações'], ['icons', Image, 'Ícones'], ['general', Settings, 'Sistema & Backup']];
  const report = (type, text) => setNotice({ type, text });
  return <div>
    <div className="page-title"><div><h2>Configuração e Integrações</h2><p>Configurações persistentes, credenciais protegidas e testes controlados.</p></div></div>
    <div className="settings-tabs">{tabs.map(([key, Icon, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon size={16} />{label}</button>)}</div>
    {notice && <div className={`notice ${notice.type}`}>{notice.text}</div>}
    {tab === 'databases' && <Databases report={report} />}
    {tab === 'notifications' && <Notifications report={report} />}
    {tab === 'icons' && <Icons report={report} />}
    {tab === 'general' && <General report={report} />}
  </div>;
}

function Databases({ report }) {
  const [items, setItems] = useState([]); const [form, setForm] = useState(databaseBlank); const [editing, setEditing] = useState(null); const [busy, setBusy] = useState(false); const [runtime,setRuntime]=useState(null);
  const [sources,setSources]=useState([]); const [source,setSource]=useState({connection_id:'',name:'',query_text:'SELECT 1 AS status',parameters:{},enabled:true});
  const load = () => Promise.all([api.get('/platform/databases'),api.get('/platform/data-sources'),api.get('/platform/database-runtime')]).then(([connections,dataSources,current])=>{setItems(connections.data);setSources(dataSources.data);setRuntime(current.data);}).catch(e => report('error', getApiErrorMessage(e)));
  useEffect(() => { load(); }, []);
  const edit = item => { setEditing(item.id); setForm({ ...item, password: '' }); };
  const save = async e => { e.preventDefault(); setBusy(true); try { editing ? await api.put(`/platform/databases/${editing}`, form) : await api.post('/platform/databases', form); report('success', 'Conexão guardada com segurança.'); setEditing(null); setForm(databaseBlank); load(); } catch(e) { report('error', getApiErrorMessage(e)); } finally { setBusy(false); } };
  const test = async id => { try { const r = await api.post(`/platform/databases/${id}/test`); report(r.data.status === 'SUCCESS' ? 'success' : 'error', r.data.message); load(); } catch(e) { report('error', getApiErrorMessage(e)); } };
  const remove = async id => { if (!confirm('Eliminar esta conexão?')) return; await api.delete(`/platform/databases/${id}`); load(); };
  const activate=async item=>{if(!confirm(`Migrar todos os dados para "${item.name}" e prepará-lo como banco principal? O banco de destino deve estar vazio.`))return;setBusy(true);try{const r=await api.post(`/platform/databases/${item.id}/activate`);report('success',`${r.data.migrated_records} registros migrados e validados. Reinicie o backend para ativar ${item.name}.`);}catch(err){report('error',getApiErrorMessage(err));}finally{setBusy(false);}};
  const createSource=async e=>{e.preventDefault();try{await api.post('/platform/data-sources',{...source,connection_id:Number(source.connection_id)});setSource({connection_id:'',name:'',query_text:'SELECT 1 AS status',parameters:{},enabled:true});report('success','Fonte de dados criada.');load();}catch(err){report('error',getApiErrorMessage(err));}};
  const testSource=async id=>{try{const r=await api.post(`/platform/data-sources/${id}/test`);report(r.data.status==='SUCCESS'?'success':'error',r.data.status==='SUCCESS'?`Consulta válida: ${r.data.row_count} linha(s).`:r.data.message);load();}catch(err){report('error',getApiErrorMessage(err));}};
  return <><div className="settings-grid"><form className="glass-card settings-panel" onSubmit={save}><h3>{editing ? 'Editar conexão' : 'Nova conexão'}</h3>
    <Field label="Nome"><input className="form-input" required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></Field>
    <div className="form-row"><Field label="Tipo"><select className="form-select" value={form.database_type} onChange={e => setForm({...form,database_type:e.target.value})}>{['POSTGRESQL','MYSQL','MSSQL','ORACLE','SQLITE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Base de dados / arquivo"><input className="form-input" required value={form.database_name} onChange={e => setForm({...form,database_name:e.target.value})}/></Field></div>
    {form.database_type !== 'SQLITE' && <><div className="form-row"><Field label="Host"><input className="form-input" required value={form.host||''} onChange={e=>setForm({...form,host:e.target.value})}/></Field><Field label="Porta"><input className="form-input" type="number" value={form.port||''} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></Field></div><div className="form-row"><Field label="Utilizador"><input className="form-input" value={form.username||''} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label={editing && form.password_configured ? 'Nova password (deixe vazia para manter)' : 'Password'}><input className="form-input" type="password" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/></Field></div></>}
    <label className="check-line"><input type="checkbox" checked={form.ssl_enabled} onChange={e=>setForm({...form,ssl_enabled:e.target.checked})}/> SSL habilitado</label><button className="btn btn-primary" disabled={busy}><Save size={16}/>Guardar conexão</button>
  </form><div className="glass-card settings-panel"><h3>Conexões configuradas</h3>{runtime&&<div className="current-database"><span>BANCO PRINCIPAL ATUAL</span><strong>{runtime.name}</strong><small>{runtime.database_type}</small></div>}{!items.length?<p className="muted">Nenhuma conexão configurada. O SQLite local permanece como banco principal.</p>:items.map(item=><div className="integration-row" key={item.id}><div><strong>{item.name}</strong><span>{item.database_type} · {item.host || item.database_name}</span></div><span className={`badge badge-${runtime?.connection_id===item.id?'online':item.last_status==='FAILED'?'offline':'unknown'}`}>{runtime?.connection_id===item.id?'PRINCIPAL':item.last_status}</span><div className="row-actions"><button className="btn btn-secondary" onClick={()=>test(item.id)}><TestTube size={14}/>Testar</button>{runtime?.connection_id!==item.id&&<button className="btn btn-primary" disabled={busy} onClick={()=>activate(item)}>Usar como principal</button>}<button className="btn btn-secondary" onClick={()=>edit(item)}>Editar</button><button className="btn btn-danger" disabled={runtime?.connection_id===item.id} onClick={()=>remove(item.id)}><Trash2 size={14}/></button></div></div>)}</div></div>
  <div className="settings-grid" style={{marginTop:'18px'}}><form className="glass-card settings-panel" onSubmit={createSource}><h3>Nova fonte de dados</h3><Field label="Conexão"><select required className="form-select" value={source.connection_id} onChange={e=>setSource({...source,connection_id:e.target.value})}><option value="">Selecione</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Nome"><input required className="form-input" value={source.name} onChange={e=>setSource({...source,name:e.target.value})}/></Field><Field label="Consulta somente leitura"><textarea required className="form-input" rows="4" value={source.query_text} onChange={e=>setSource({...source,query_text:e.target.value})}/></Field><button className="btn btn-primary"><Plus size={15}/>Criar fonte</button></form><div className="glass-card settings-panel"><h3>Fontes disponíveis</h3>{!sources.length?<p className="muted">Nenhuma fonte configurada.</p>:sources.map(x=><div className="integration-row" key={x.id}><div><strong>{x.name}</strong><span>{items.find(i=>i.id===x.connection_id)?.name} · SELECT limitado a 100 linhas</span></div><span className={`badge badge-${x.last_status==='SUCCESS'?'online':x.last_status==='FAILED'?'offline':'unknown'}`}>{x.last_status}</span><div className="row-actions"><button className="btn btn-secondary" onClick={()=>testSource(x.id)}><TestTube size={14}/>Executar</button><button className="btn btn-danger" onClick={async()=>{if(confirm('Eliminar fonte?')){await api.delete(`/platform/data-sources/${x.id}`);load();}}}><Trash2 size={14}/></button></div></div>)}</div></div></>;
}

function Notifications({ report }) {
  const [providers, setProviders] = useState(providerDefaults); const [rules, setRules] = useState([]); const [rule, setRule] = useState({ name:'',event_type:'LINK_DOWN',severity:'CRITICAL',source:'',channels:['EMAIL'],recipients:[],reminder_minutes:0,notify_recovery:true,enabled:true });
  const load = async()=>{ const [p,r]=await Promise.all([api.get('/platform/notifications'),api.get('/platform/notification-rules')]); const merged={...providerDefaults}; p.data.forEach(x=>{merged[x.provider]={...providerDefaults[x.provider],...x,config:{...providerDefaults[x.provider].config,...x.config},secrets:{...providerDefaults[x.provider].secrets}}}); setProviders(merged); setRules(r.data); };
  useEffect(()=>{load().catch(e=>report('error',getApiErrorMessage(e)));},[]);
  const change=(key,section,field,value)=>setProviders(old=>({...old,[key]:{...old[key],[section]:{...old[key][section],[field]:value}}}));
  const save=async key=>{try{await api.put(`/platform/notifications/${key}`,providers[key]);report('success',`${providers[key].name} guardado.`);load();}catch(e){report('error',getApiErrorMessage(e));}};
  const test=async key=>{try{const r=await api.post(`/platform/notifications/${key}/test`);report(r.data.status==='SUCCESS'?'success':'error',r.data.message);load();}catch(e){report('error',getApiErrorMessage(e));}};
  const createRule=async e=>{e.preventDefault();try{await api.post('/platform/notification-rules',{...rule,recipients:typeof rule.recipients==='string'?rule.recipients.split(',').map(x=>x.trim()).filter(Boolean):rule.recipients});report('success','Regra criada.');load();}catch(e){report('error',getApiErrorMessage(e));}};
  return <><div className="provider-grid">{Object.entries(providers).map(([key,p])=><div className="glass-card settings-panel" key={key}><div className="panel-heading"><h3>{p.name}</h3><label className="switch-label"><input type="checkbox" checked={p.enabled} onChange={e=>setProviders(o=>({...o,[key]:{...p,enabled:e.target.checked}}))}/> Ativo</label></div>
    {key==='EMAIL'&&<><Field label="Servidor SMTP"><input className="form-input" value={p.config.smtp_server} onChange={e=>change(key,'config','smtp_server',e.target.value)}/></Field><div className="form-row"><Field label="Porta"><input className="form-input" type="number" value={p.config.smtp_port} onChange={e=>change(key,'config','smtp_port',Number(e.target.value))}/></Field><Field label="Utilizador"><input className="form-input" value={p.config.username} onChange={e=>change(key,'config','username',e.target.value)}/></Field></div><Field label="Password"><input className="form-input" type="password" placeholder={p.secrets_configured?.includes('password')?'Configurada — preencher apenas para alterar':''} value={p.secrets.password} onChange={e=>change(key,'secrets','password',e.target.value)}/></Field><Field label="Remetente"><input className="form-input" value={p.config.from_address} onChange={e=>change(key,'config','from_address',e.target.value)}/></Field><Field label="Destinatários (vírgula)"><input className="form-input" value={(p.config.recipients||[]).join(', ')} onChange={e=>change(key,'config','recipients',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field></>}
    {key==='TELEGRAM'&&<><Field label="Bot token"><input className="form-input" type="password" placeholder={p.secrets_configured?.includes('bot_token')?'Token configurado':''} value={p.secrets.bot_token} onChange={e=>change(key,'secrets','bot_token',e.target.value)}/></Field><Field label="Chat ID"><input className="form-input" value={p.config.chat_id} onChange={e=>change(key,'config','chat_id',e.target.value)}/></Field></>}
    {key==='WHATSAPP'&&<><Field label="URL da API oficial/provider"><input className="form-input" value={p.config.api_url} onChange={e=>change(key,'config','api_url',e.target.value)}/></Field><Field label="API token"><input className="form-input" type="password" placeholder={p.secrets_configured?.includes('api_token')?'Token configurado':''} value={p.secrets.api_token} onChange={e=>change(key,'secrets','api_token',e.target.value)}/></Field><div className="form-row"><Field label="Sender ID"><input className="form-input" value={p.config.sender_id} onChange={e=>change(key,'config','sender_id',e.target.value)}/></Field><Field label="Destinatário"><input className="form-input" value={p.config.recipient} onChange={e=>change(key,'config','recipient',e.target.value)}/></Field></div></>}
    <div className="row-actions"><button className="btn btn-primary" onClick={()=>save(key)}><Save size={14}/>Guardar</button><button className="btn btn-secondary" onClick={()=>test(key)}><TestTube size={14}/>Testar</button></div></div>)}</div>
    <div className="settings-grid"><form className="glass-card settings-panel" onSubmit={createRule}><h3>Nova regra de notificação</h3><Field label="Nome"><input required className="form-input" value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></Field><div className="form-row"><Field label="Evento"><select className="form-select" value={rule.event_type} onChange={e=>setRule({...rule,event_type:e.target.value})}>{['DEVICE_DOWN','DEVICE_UP','LINK_DOWN','LINK_UP','REDUNDANCY_DEGRADED','REDUNDANCY_CRITICAL','RECOVERY'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Severidade"><select className="form-select" value={rule.severity} onChange={e=>setRule({...rule,severity:e.target.value})}>{['INFO','WARNING','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Canais"><div className="method-options">{['EMAIL','TELEGRAM','WHATSAPP'].map(x=><label key={x}><input type="checkbox" checked={rule.channels.includes(x)} onChange={()=>setRule({...rule,channels:rule.channels.includes(x)?rule.channels.filter(y=>y!==x):[...rule.channels,x]})}/>{x}</label>)}</div></Field><Field label="Destinatários adicionais (vírgula)"><input className="form-input" value={rule.recipients} onChange={e=>setRule({...rule,recipients:e.target.value})}/></Field><button className="btn btn-primary"><Plus size={15}/>Criar regra</button></form><div className="glass-card settings-panel"><h3>Regras ativas</h3>{rules.map(r=><div className="integration-row" key={r.id}><div><strong>{r.name}</strong><span>{r.event_type} · {r.channels.join(' + ')}</span></div><span className={`badge badge-${r.enabled?'online':'unknown'}`}>{r.enabled?'ATIVA':'INATIVA'}</span><button className="btn btn-danger" onClick={async()=>{if(confirm('Eliminar regra?')){await api.delete(`/platform/notification-rules/${r.id}`);load();}}}><Trash2 size={14}/></button></div>)}</div></div></>;
}

function Icons({ report }) { const [icons,setIcons]=useState([]); const [name,setName]=useState(''); const [file,setFile]=useState(null); const load=()=>api.get('/platform/icons').then(r=>setIcons(r.data)); useEffect(()=>{load();},[]); const upload=async e=>{e.preventDefault();const data=new FormData();data.append('name',name);data.append('category','Custom');data.append('file',file);try{await api.post('/platform/icons',data,{headers:{'Content-Type':'multipart/form-data'}});report('success','Ícone carregado.');setName('');setFile(null);load();}catch(err){report('error',getApiErrorMessage(err));}}; return <div className="settings-grid"><form className="glass-card settings-panel" onSubmit={upload}><h3>Ícone personalizado</h3><p className="muted">SVG sanitizado ou PNG, até 512 KB.</p><Field label="Nome"><input className="form-input" required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Arquivo"><input className="form-input" required type="file" accept=".svg,.png,image/svg+xml,image/png" onChange={e=>setFile(e.target.files[0])}/></Field><button className="btn btn-primary"><Upload size={15}/>Carregar</button></form><div className="glass-card settings-panel"><h3>Biblioteca ({icons.length})</h3><div className="icon-library">{icons.map(i=><div key={i.id}><span>{i.lucide_name||'SVG/PNG'}</span><strong>{i.name}</strong><small>{i.category}</small></div>)}</div></div></div> }

function General({ report }) { const [form,setForm]=useState({timezone:'UTC',retention_days:90,default_monitoring_interval:30,failure_threshold:3,success_threshold:2}); useEffect(()=>{api.get('/platform/settings').then(r=>setForm(r.data));},[]); const save=async e=>{e.preventDefault();try{await api.put('/platform/settings',form);report('success','Configurações persistidas.');}catch(err){report('error',getApiErrorMessage(err));}}; const backup=async()=>{const r=await api.get('/platform/configuration/export');const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`netmonitor-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}; const restore=async file=>{try{const payload=JSON.parse(await file.text());const r=await api.post('/platform/configuration/import',payload);report('success',`Backup importado: ${Object.values(r.data.counts).reduce((a,b)=>a+b,0)} registros processados.`);}catch(err){report('error',getApiErrorMessage(err));}}; return <div className="settings-grid"><form className="glass-card settings-panel" onSubmit={save}><h3>Preferências persistentes</h3><Field label="Timezone"><input className="form-input" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field><div className="form-row"><Field label="Retenção (dias)"><input className="form-input" type="number" value={form.retention_days} onChange={e=>setForm({...form,retention_days:Number(e.target.value)})}/></Field><Field label="Intervalo padrão (s)"><input className="form-input" type="number" value={form.default_monitoring_interval} onChange={e=>setForm({...form,default_monitoring_interval:Number(e.target.value)})}/></Field></div><button className="btn btn-primary"><Save size={15}/>Guardar</button></form><div className="glass-card settings-panel"><h3>Backup e restauração</h3><p className="muted">Credenciais nunca são incluídas no arquivo exportado.</p><div className="backup-actions"><button className="btn btn-primary" onClick={backup}><Download size={15}/>Exportar configuração</button><label className="btn btn-secondary"><Upload size={15}/>Importar backup<input hidden type="file" accept="application/json" onChange={e=>e.target.files[0]&&restore(e.target.files[0])}/></label></div></div></div> }

function Field({ label, children }) { return <div className="form-group"><label className="form-label">{label}</label>{children}</div>; }
