import React, { useEffect, useState } from 'react';
import { Activity, ArrowLeft, Clock3, Gauge, RefreshCw, ServerCog, ShieldCheck, TimerOff } from 'lucide-react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

const periods=[['24h','24 hours'],['7d','7 days'],['30d','30 days'],['90d','90 days']];
const formatDate=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'medium'}).format(new Date(value)):'Ongoing';
const formatAxis=value=>new Intl.DateTimeFormat(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const formatDuration=seconds=>{const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return[days&&`${days}d`,hours&&`${hours}h`,`${minutes}m`].filter(Boolean).join(' ')};
const tooltipStyle={background:'var(--bg-surface)',border:'1px solid var(--border-color)',borderRadius:10,color:'var(--text-main)'};

export default function ServiceAnalytics(){
  const {serviceId}=useParams();const navigate=useNavigate();const location=useLocation();const [period,setPeriod]=useState('24h');const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const returnTo=new URLSearchParams(location.search).get('from')==='topology'?'/service-topology':'/service-monitoring';
  const load=()=>{setLoading(true);setError('');api.get(`/services/${serviceId}/analytics?period=${period}`).then(r=>setData(r.data)).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false));};
  useEffect(load,[serviceId,period]);
  if(loading&&!data)return <div className="analytics-state"><Activity className="spin" size={30}/><span>Loading service metrics…</span></div>;
  if(error&&!data)return <div className="notice error">{error}</div>;
  const service=data?.service||{},summary=data?.summary||{},series=data?.series||[];
  return <div className="service-analytics-page"><div className="analytics-header"><div className="analytics-heading"><button className="icon-button" onClick={()=>navigate(returnTo)}><ArrowLeft size={18}/></button><div><div className="analytics-title-line"><h2>{service.display_name}</h2><span className={`badge badge-${service.monitor_state==='UP'?'online':service.monitor_state==='DOWN'?'offline':'unknown'}`}>{service.monitor_state}</span></div><p>{service.device_name} · {service.ip_address||'No IP'} · {service.name}</p></div></div><div className="period-selector">{periods.map(([value,label])=><button key={value} className={period===value?'active':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div></div>
    {error&&<div className="notice error">Could not refresh service metrics: {error}</div>}
    <div className="metric-summary-grid"><Summary icon={ShieldCheck} label="Availability" value={summary.availability_pct==null?'No data':`${summary.availability_pct}%`} note={`${summary.successful_checks||0} successful of ${summary.total_checks||0} checks`}/><Summary icon={Gauge} label="Average response" value={summary.average_response_ms==null?'—':`${summary.average_response_ms} ms`} note={`Maximum ${summary.maximum_response_ms==null?'—':`${summary.maximum_response_ms} ms`}`}/><Summary icon={RefreshCw} label="Transitions" value={`${summary.failure_events||0} / ${summary.recovery_events||0}`} note="Failures / recoveries"/><Summary icon={TimerOff} label="Downtime" value={formatDuration(summary.downtime_seconds||0)} note={`${summary.outage_count||0} confirmed outage(s)`} tone="critical"/></div>
    <div className="analytics-grid"><section className="glass-card analytics-panel analytics-chart-wide"><div className="panel-title"><div><h3>Response time and availability</h3><p>Aggregated Windows service checks during the selected period</p></div><span>{series.length} data points</span></div>{series.length?<div className="chart-container"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={series}><defs><linearGradient id="serviceResponse" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3b82f6" stopOpacity={.42}/><stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.06)"/><XAxis dataKey="timestamp" tickFormatter={formatAxis} minTickGap={45} stroke="#64748b" fontSize={11}/><YAxis yAxisId="response" unit=" ms" stroke="#64748b" fontSize={11}/><YAxis yAxisId="availability" orientation="right" domain={[0,100]} unit="%" stroke="#64748b" fontSize={11}/><Tooltip contentStyle={tooltipStyle} labelFormatter={formatDate}/><Area yAxisId="response" type="monotone" dataKey="response_ms" name="Response" stroke="#3b82f6" fill="url(#serviceResponse)" connectNulls/><Line yAxisId="availability" type="monotone" dataKey="availability_pct" name="Availability" stroke="#22c55e" strokeWidth={2}/></ComposedChart></ResponsiveContainer></div>:<Empty/>}</section>
      <section className="glass-card analytics-panel"><div className="panel-title"><div><h3>Health timeline</h3><p>UP, suspected, down, recovering, and unknown states</p></div></div>{series.length?<div className="availability-strip">{series.map((point,index)=><span key={`${point.timestamp}-${index}`} className={`status-${stateClass(point.status)}`} title={`${formatDate(point.timestamp)} — ${point.status}`}/>)}</div>:<Empty/>}</section>
      <section className="glass-card analytics-panel"><div className="panel-title"><div><h3>Monitoring policy</h3><p>Current configuration for this service</p></div></div><dl className="device-facts"><Fact label="Observed" value={service.state}/><Fact label="Expected" value={service.expected_state}/><Fact label="Start mode" value={service.start_mode}/><Fact label="Interval" value={`${service.check_interval}s`}/><Fact label="Failure handling" value="Immediate DOWN"/><Fact label="Recovery threshold" value={service.recovery_threshold}/><Fact label="Severity" value={service.severity}/><Fact label="Communication errors" value={summary.communication_errors||0}/></dl></section></div>
    <section className="glass-card analytics-panel outage-panel"><div className="panel-title"><div><h3>Confirmed service outages</h3><p>Starts only after the configured failure threshold is reached</p></div><Clock3 size={20}/></div>{data?.outages?.length?<div className="outage-table-wrap"><table className="custom-table"><thead><tr><th>Started</th><th>Recovered</th><th>Duration</th><th>State</th></tr></thead><tbody>{data.outages.map(x=><tr key={x.started_at}><td>{formatDate(x.started_at)}</td><td>{formatDate(x.ended_at)}</td><td>{formatDuration(x.duration_seconds)}</td><td><span className={`badge ${x.ongoing?'badge-critical':'badge-online'}`}>{x.ongoing?'ONGOING':'RECOVERED'}</span></td></tr>)}</tbody></table></div>:<div className="no-outages"><ShieldCheck size={24}/><div><strong>No confirmed outages</strong><span>No DOWN transition was recorded in this period.</span></div></div>}</section>
    <section className="glass-card analytics-panel service-check-history"><div className="panel-title"><div><h3>Recent checks</h3><p>Operational result and communication classification</p></div></div><div className="outage-table-wrap"><table className="custom-table"><thead><tr><th>Checked</th><th>Observed</th><th>Health</th><th>Response</th><th>Error</th></tr></thead><tbody>{data?.history?.map(x=><tr key={x.id}><td>{formatDate(x.checked_at)}</td><td>{x.observed_state}</td><td><span className={`badge badge-${x.monitor_state==='UP'?'online':x.monitor_state==='DOWN'?'offline':'unknown'}`}>{x.monitor_state}</span></td><td>{x.response_ms==null?'—':`${x.response_ms} ms`}</td><td>{x.error_code||'—'}</td></tr>)}</tbody></table></div></section>
  </div>;
}
function stateClass(state){return state==='UP'?'up':state==='DOWN'?'down':state==='SUSPECTED'||state==='RECOVERING'?'degraded':'unknown'}
function Summary({icon:Icon,label,value,note,tone=''}){return <div className={`metric-summary-card ${tone}`}><Icon/><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Fact({label,value}){return <div><dt>{label}</dt><dd>{value??'—'}</dd></div>}
function Empty(){return <div className="chart-empty"><ServerCog size={28}/><strong>No service check data</strong><span>Metrics appear after the monitoring engine records checks.</span></div>}
