import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Maximize2, RefreshCw } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import ReactFlow, { Background, Controls, MiniMap, MarkerType, Position } from 'reactflow';
import 'reactflow/dist/style.css';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

const colors={UP:'#22c55e',DOWN:'#ef4444',SUSPECTED:'#f59e0b',RECOVERING:'#f59e0b',UNKNOWN:'#64748b'};
export default function ServiceTopology() {
  const [params,setParams]=useSearchParams(); const board=useRef(null); const [data,setData]=useState({devices:[],services:[],edges:[]}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const selected=params.get('device')||''; const load=()=>{setLoading(true);setError('');api.get('/services/topology').then(r=>setData(r.data)).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false));}; useEffect(load,[]);
  const graph=useMemo(()=>{const devices=selected?data.devices.filter(x=>String(x.id)===selected):data.devices;const visibleIds=new Set(devices.map(x=>x.id));const services=data.services.filter(x=>visibleIds.has(x.device_id));const nodes=[];devices.forEach((device,column)=>{const own=services.filter(x=>x.device_id===device.id);const x=column*360;nodes.push({id:`device-${device.id}`,position:{x,y:20},sourcePosition:Position.Bottom,targetPosition:Position.Top,data:{label:<div className="rf-device-node"><strong>{device.name}</strong><span>{device.ip_address||device.location}</span><b>{device.status}</b></div>},style:{width:250,border:`1px solid ${device.status==='ONLINE'?'#3b82f6':'#ef4444'}`,borderRadius:12,background:'#111827',color:'#fff',padding:0}});own.forEach((service,row)=>nodes.push({id:`service-${service.id}`,position:{x:x+15,y:155+row*105},sourcePosition:Position.Bottom,targetPosition:Position.Top,data:{label:<div className="rf-service-node"><span style={{background:colors[service.monitor_state]}}/><div><strong>{service.display_name}</strong><small>{service.name} · {service.state}</small></div><b style={{color:colors[service.monitor_state]}}>{service.monitor_state}</b></div>},style:{width:220,border:`1px solid ${colors[service.monitor_state]}`,borderRadius:10,background:'#0f172a',color:'#fff',padding:0}}));});const edges=services.map(service=>({id:`edge-${service.id}`,source:`device-${service.device_id}`,target:`service-${service.id}`,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed,color:colors[service.monitor_state]},style:{stroke:colors[service.monitor_state],strokeWidth:1.5},animated:['DOWN','SUSPECTED'].includes(service.monitor_state)}));return{nodes,edges};},[data,selected]);
  return <div className="data-page"><div className="page-title"><div><h2>Service Topology</h2><p>Interactive device-to-service map with zoom, pan, minimap, and live state.</p></div><div className="row-actions"><select className="form-select compact" value={selected} onChange={e=>setParams(e.target.value?{device:e.target.value}:{})}><option value="">All monitored devices</option>{data.devices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn btn-secondary" onClick={load}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button><button className="btn btn-secondary" onClick={()=>board.current?.requestFullscreen?.()}><Maximize2 size={15}/>Fullscreen</button></div></div>{error&&<div className="notice error">{error}</div>}<section ref={board} className="glass-card service-reactflow-board">{!graph.nodes.length?<div className="service-placeholder"><Activity size={38}/><strong>No monitored service topology</strong><span>Discover and configure services first.</span></div>:<ReactFlow nodes={graph.nodes} edges={graph.edges} fitView fitViewOptions={{padding:.2}} minZoom={.15} maxZoom={1.8} nodesDraggable nodesConnectable={false} elementsSelectable><Background color="#334155" gap={22}/><MiniMap pannable zoomable nodeColor={node=>node.id.startsWith('device-')?'#3b82f6':'#64748b'}/><Controls showInteractive={false}/></ReactFlow>}</section></div>;
}
