import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, LayoutGrid, Maximize2, Minimize2, Move, RefreshCw, RotateCcw, Save, Trash2 } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import ReactFlow, { Background, Controls, MarkerType, MiniMap, Position, useEdgesState, useNodesState } from 'reactflow';
import 'reactflow/dist/style.css';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

const colors={UP:'#22c55e',DOWN:'#ef4444',SUSPECTED:'#f59e0b',RECOVERING:'#f59e0b',UNKNOWN:'#64748b'};

function buildGraph(data,selected) {
  const devices=selected?data.devices.filter(x=>String(x.id)===selected):data.devices;
  const visibleIds=new Set(devices.map(x=>x.id)); const services=data.services.filter(x=>visibleIds.has(x.device_id)); const nodes=[];
  devices.forEach((device,column)=>{const own=services.filter(x=>x.device_id===device.id);const x=column*360;
    nodes.push({id:`device-${device.id}`,type:'default',position:{x,y:20},sourcePosition:Position.Bottom,targetPosition:Position.Top,data:{kind:'device',record:device,label:<div className="rf-device-node"><strong>{device.name}</strong><span>{device.ip_address||device.location}</span><b>{device.status}</b></div>},style:{width:250,border:`1px solid ${device.status==='ONLINE'?'#3b82f6':'#ef4444'}`,borderRadius:12,background:'#111827',color:'#fff',padding:0}});
    own.forEach((service,row)=>nodes.push({id:`service-${service.id}`,position:{x:x+15,y:155+row*105},sourcePosition:Position.Bottom,targetPosition:Position.Top,data:{kind:'service',record:service,label:<div className="rf-service-node"><span style={{background:colors[service.monitor_state]}}/><div><strong>{service.display_name}</strong><small>{service.name} · {service.state}</small></div><b style={{color:colors[service.monitor_state]}}>{service.monitor_state}</b></div>},style:{width:220,border:`1px solid ${colors[service.monitor_state]}`,borderRadius:10,background:'#0f172a',color:'#fff',padding:0}}));
  });
  const edges=services.map(service=>({id:`edge-${service.id}`,source:`device-${service.device_id}`,target:`service-${service.id}`,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed,color:colors[service.monitor_state]},style:{stroke:colors[service.monitor_state],strokeWidth:1.5},animated:['DOWN','SUSPECTED'].includes(service.monitor_state)}));
  return {nodes,edges};
}

export default function ServiceTopology() {
  const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const container=useRef(null); const flow=useRef(null); const pendingViewport=useRef(null);
  const [data,setData]=useState({devices:[],services:[],edges:[]}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [layout,setLayout]=useState('auto'); const [fullscreen,setFullscreen]=useState(false);
  const [nodes,setNodes,onNodesChange]=useNodesState([]); const [edges,setEdges,onEdgesChange]=useEdgesState([]); const [views,setViews]=useState([]); const [viewId,setViewId]=useState(''); const [savedPositions,setSavedPositions]=useState({});
  const nodesRef=useRef([]); const layoutRef=useRef('auto');
  const selected=params.get('device')||''; const generated=useMemo(()=>buildGraph(data,selected),[data,selected]);
  const load=()=>{setLoading(true);setError('');api.get('/services/topology').then(r=>setData(r.data)).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false));};
  useEffect(()=>{load();api.get('/platform/service-topology-layout').then(({data:stored})=>{setLayout(stored.layout_mode||'auto');setSavedPositions(Object.fromEntries((stored.positions||[]).map(x=>[x.node_id,{x:x.x,y:x.y}])));pendingViewport.current=Number.isFinite(stored.viewport?.zoom)?stored.viewport:null;if(flow.current&&pendingViewport.current)flow.current.setViewport(pendingViewport.current,{duration:0});});api.get('/platform/service-topology-layout/snapshots').then(r=>setViews(r.data));const timer=setInterval(load,5000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{setNodes(generated.nodes.map(n=>({...n,position:layout==='free'&&savedPositions[n.id]?savedPositions[n.id]:n.position})));setEdges(generated.edges);},[generated,layout,savedPositions,setNodes,setEdges]);
  useEffect(()=>{nodesRef.current=nodes;layoutRef.current=layout;if(nodes.length&&flow.current&&pendingViewport.current){flow.current.setViewport(pendingViewport.current,{duration:0});pendingViewport.current=null;}},[nodes,layout]);
  useEffect(()=>{const listener=()=>setFullscreen(document.fullscreenElement===container.current);document.addEventListener('fullscreenchange',listener);return()=>document.removeEventListener('fullscreenchange',listener);},[]);
  useEffect(()=>{let timer;const saveViewport=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!flow.current||!nodesRef.current.length)return;api.put('/platform/service-topology-layout',{layout_mode:layoutRef.current,positions:nodesRef.current.map(n=>({node_id:n.id,x:n.position.x,y:n.position.y})),viewport:flow.current.getViewport()}).catch(()=>{});},250);};const element=container.current;if(!element)return;element.addEventListener('wheel',saveViewport,{passive:true});element.addEventListener('pointerup',saveViewport);return()=>{clearTimeout(timer);element.removeEventListener('wheel',saveViewport);element.removeEventListener('pointerup',saveViewport);};},[nodes.length]);
  const payload=current=>({layout_mode:layout,positions:current.map(n=>({node_id:n.id,x:n.position.x,y:n.position.y})),viewport:flow.current?.getViewport?.()||{}});
  const persist=(current,mode=layout)=>{const positions=Object.fromEntries(current.map(n=>[n.id,n.position]));setSavedPositions(positions);api.put('/platform/service-topology-layout',{...payload(current),layout_mode:mode}).catch(e=>setError(getApiErrorMessage(e)));};
  const dragStop=(_,node)=>{if(layout!=='free')return;setNodes(current=>{const next=current.map(x=>x.id===node.id?{...x,position:node.position}:x);persist(next);return next;});};
  const reorganize=()=>{setNodes(generated.nodes);persist(generated.nodes);setTimeout(()=>flow.current?.fitView({padding:.2,duration:350}),0);};
  const changeLayout=value=>{setLayout(value);if(value==='auto'){setNodes(generated.nodes);persist(generated.nodes,value);setTimeout(()=>flow.current?.fitView({padding:.2,duration:350}),0);}else persist(nodes,value);};
  const toggleFullscreen=async()=>document.fullscreenElement===container.current?document.exitFullscreen():container.current?.requestFullscreen?.();
  const reloadViews=()=>api.get('/platform/service-topology-layout/snapshots').then(r=>setViews(r.data));
  const snapshotPayload=name=>({name,...payload(nodes)});
  const newView=async()=>{const name=window.prompt('View/layout name:',`View ${new Date().toLocaleString('en-GB')}`)?.trim();if(!name)return;try{const {data:item}=await api.post('/platform/service-topology-layout/snapshots',snapshotPayload(name));await reloadViews();setViewId(String(item.id));}catch(e){setError(getApiErrorMessage(e));}};
  const saveView=async()=>{if(!viewId)return newView();const view=views.find(v=>String(v.id)===viewId);if(!view)return newView();try{await api.put(`/platform/service-topology-layout/snapshots/${viewId}`,snapshotPayload(view.name));await reloadViews();}catch(e){setError(getApiErrorMessage(e));}};
  const restoreView=async()=>{if(!viewId)return;try{const {data:view}=await api.post(`/platform/service-topology-layout/snapshots/${viewId}/restore`);const positions=Object.fromEntries((view.positions||[]).map(x=>[x.node_id,{x:x.x,y:x.y}]));setLayout(view.layout_mode||'free');setSavedPositions(positions);setNodes(current=>current.map(n=>({...n,position:positions[n.id]||n.position})));if(Number.isFinite(view.viewport?.zoom))setTimeout(()=>flow.current?.setViewport(view.viewport,{duration:350}),0);}catch(e){setError(getApiErrorMessage(e));}};
  const deleteView=async()=>{if(!viewId||!window.confirm('Delete this saved view?'))return;try{await api.delete(`/platform/service-topology-layout/snapshots/${viewId}`);setViewId('');await reloadViews();}catch(e){setError(getApiErrorMessage(e));}};
  const openNode=(_,node)=>node.data.kind==='service'?navigate(`/services/${node.data.record.id}?from=topology`):navigate(`/devices/${node.data.record.id}?from=service-topology`);

  return <div className="data-page"><div className="page-title"><div><h2>Service Topology</h2><p>Live topology with reusable views, automatic or free layout, zoom, pan, and fullscreen.</p></div><div className="row-actions"><select className="form-select compact" value={selected} onChange={e=>setParams(e.target.value?{device:e.target.value}:{})}><option value="">All monitored devices</option>{data.devices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn btn-secondary" onClick={load}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button></div></div>{error&&<div className="notice error">{error}</div>}
    <section ref={container} className="glass-card service-reactflow-board topology-canvas">{!nodes.length?<div className="service-placeholder"><Activity size={38}/><strong>No monitored service topology</strong><span>Discover and add services first.</span></div>:<><div className="service-topology-toolbar"><select className="form-select compact" value={viewId} onChange={e=>setViewId(e.target.value)}><option value="">My saved views…</option>{views.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><button className="btn btn-secondary" onClick={saveView}><Save size={14}/>{viewId?'Save':'Save View'}</button><button className="btn btn-secondary" onClick={newView}>+ New View</button><button className="btn btn-secondary" disabled={!viewId} onClick={restoreView}><RotateCcw size={14}/>Restore</button><button className="btn btn-danger" disabled={!viewId} onClick={deleteView}><Trash2 size={14}/></button><button className={`btn ${layout==='auto'?'btn-primary':'btn-secondary'}`} onClick={()=>changeLayout('auto')}><LayoutGrid size={14}/>Automatic</button><button className={`btn ${layout==='free'?'btn-primary':'btn-secondary'}`} onClick={()=>changeLayout('free')}><Move size={14}/>Free</button><button className="btn btn-secondary" onClick={reorganize}>Reorganize</button><button className="btn btn-secondary" onClick={toggleFullscreen}>{fullscreen?<Minimize2 size={14}/>:<Maximize2 size={14}/>} {fullscreen?'Exit':'Fullscreen'}</button></div><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeDragStop={dragStop} onNodeDoubleClick={openNode} onInit={instance=>flow.current=instance} fitView fitViewOptions={{padding:.2}} minZoom={.15} maxZoom={1.8} nodesDraggable={layout==='free'} nodesConnectable={false} elementsSelectable><Background color="#334155" gap={22}/><MiniMap pannable zoomable nodeColor={node=>node.id.startsWith('device-')?'#3b82f6':colors[node.data?.record?.monitor_state]||'#64748b'}/><Controls showInteractive={false}/></ReactFlow></>}</section>
  </div>;
}
