import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle, GitBranch, Plus, RefreshCw, Server, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../api/client';
import { getApiErrorMessage } from '../utils/errors';

export default function ServiceMonitoring() {
  const navigate=useNavigate(); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=()=>{setLoading(true);setError('');api.get('/services/overview').then(r=>setData(r.data)).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const summary=data?.summary||{};
  return <div className="data-page service-monitoring-dashboard"><div className="page-title"><div><h2>Service Monitoring</h2><p>Operational health of explicitly monitored services across every device.</p></div><div className="row-actions"><button className="btn btn-secondary" onClick={load} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button><button className="btn btn-secondary" onClick={()=>navigate('/service-topology')}><GitBranch size={15}/>Service Topology</button><button className="btn btn-primary" onClick={()=>navigate('/service-discovery')}><Plus size={15}/>Add Services</button></div></div>{error&&<div className="notice error">{error}</div>}
    <div className="service-kpi-grid"><Kpi icon={Activity} label="Monitored services" value={summary.total||0}/><Kpi icon={CheckCircle} label="Healthy" value={summary.up||0} tone="healthy"/><Kpi icon={ShieldAlert} label="Need attention" value={(summary.down||0)+(summary.suspected||0)+(summary.recovering||0)+(summary.unknown||0)} tone="danger"/><Kpi icon={Server} label="Covered devices" value={summary.devices||0}/></div>
    {!loading&&summary.total===0?<div className="glass-card service-onboarding"><div className="service-onboarding-icon"><Activity size={34}/></div><div><h3>No services are monitored yet</h3><p>Use the guided discovery workflow to connect a Windows device, review its services, and select only the services that matter.</p></div><button className="btn btn-primary" onClick={()=>navigate('/service-discovery')}>Start Service Discovery</button></div>:<div className="service-dashboard-grid"><section className="glass-card analytics-panel"><div className="panel-title"><div><h3>Health by device</h3><p>Reachability and service health are evaluated separately.</p></div></div><div className="service-device-list">{data?.devices.map(x=><button key={x.device_id} onClick={()=>navigate(`/service-topology?device=${x.device_id}`)}><span className={`service-health-dot state-${x.service_health.toLowerCase()}`}/><div><strong>{x.device_name}</strong><small>{x.ip_address||'No IP'} · {x.total} monitored</small></div><span className={`badge badge-${x.service_health==='UP'?'online':x.service_health==='DOWN'?'offline':'unknown'}`}>{x.service_health}</span></button>)}</div></section><section className="glass-card analytics-panel"><div className="panel-title"><div><h3>Requires attention</h3><p>Confirmed and transitional service states.</p></div><AlertTriangle size={20}/></div>{!data?.attention.length?<div className="service-placeholder"><CheckCircle size={30}/><span>All monitored services are healthy.</span></div>:<div className="service-attention-list">{data.attention.map(x=><article key={x.id}><div><strong>{x.display_name}</strong><small>{x.device_name} · expected {x.expected_state}</small></div><span className={`badge badge-${x.monitor_state==='DOWN'?'offline':'unknown'}`}>{x.monitor_state}</span></article>)}</div>}</section></div>}
    {data?.recent?.length>0&&<section className="glass-card analytics-panel service-recent"><div className="panel-title"><div><h3>Recent service status</h3><p>Latest checks across the monitoring estate.</p></div></div><table className="custom-table"><thead><tr><th>Device</th><th>Service</th><th>Observed</th><th>Expected</th><th>Health</th><th>Last checked</th></tr></thead><tbody>{data.recent.map(x=><tr key={x.id}><td>{x.device_name}</td><td><strong>{x.display_name}</strong><small>{x.name}</small></td><td>{x.state}</td><td>{x.expected_state}</td><td><span className={`badge badge-${x.monitor_state==='UP'?'online':x.monitor_state==='DOWN'?'offline':'unknown'}`}>{x.monitor_state}</span></td><td>{x.last_checked_at?new Date(x.last_checked_at).toLocaleString():'Waiting for first check'}</td></tr>)}</tbody></table></section>}
  </div>;
}
function Kpi({icon:Icon,label,value,tone=''}) { return <div className={`glass-card service-kpi ${tone}`}><Icon size={22}/><div><span>{label}</span><strong>{value}</strong></div></div>; }
